default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= Rails.application.config.sql_path_dev %>

development:
  <<: *default
  database: <%= Rails.application.config.sql_path_dev %>

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
